# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cvy < Formula
  desc "Provision coordinated Claude Code sessions across multiple repos"
  homepage "https://github.com/timothylippiatt/convoy"
  version "0.2.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/timothylippiatt/convoy/releases/download/v0.2.1/convoy_0.2.1_darwin_amd64.tar.gz"
      sha256 "d3b0f5187ecebafb797f65aeeac2ec0d0bc72d5aad4c12b44dffe597af4cf9f3"

      define_method(:install) do
        bin.install "cvy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/timothylippiatt/convoy/releases/download/v0.2.1/convoy_0.2.1_darwin_arm64.tar.gz"
      sha256 "59a92a11dcc51e7328bd9888eee26753a9a37c73c48270c9a83897b5a501f481"

      define_method(:install) do
        bin.install "cvy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/timothylippiatt/convoy/releases/download/v0.2.1/convoy_0.2.1_linux_amd64.tar.gz"
      sha256 "667ee07a32ce403f55388ebba8ff548ecd4008b6233f5b40d8f3771697431026"
      define_method(:install) do
        bin.install "cvy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/timothylippiatt/convoy/releases/download/v0.2.1/convoy_0.2.1_linux_arm64.tar.gz"
      sha256 "7fccddf0cd6bc2db63916b395642b498fddb911342321e729317b47269c17231"
      define_method(:install) do
        bin.install "cvy"
      end
    end
  end

  test do
    system "#{bin}/cvy version"
  end
end
